# Generated by Django 4.0.2 on 2022-02-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_name', models.CharField(max_length=30)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fill_amt', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=60)),
                ('store_longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('store_latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('typical_amt_1', models.IntegerField()),
                ('typical_amt_2', models.IntegerField()),
                ('typical_amt_3', models.IntegerField()),
                ('typical_amt_4', models.IntegerField()),
                ('envelope', models.ManyToManyField(related_name='store', to='globalspend_app.Envelope')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('original_transaction_amt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('home_transaction_amt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_debit_transaction', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='globalspend_app.envelope')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='globalspend_app.store')),
            ],
        ),
    ]
